### ISSUE TITLE
Forgot to add 'labels'

### ISSUE THREAD

**Issue by lordnox** [romgrk/node-todoist#2]
https://github.com/romgrk/node-todoist/blob/4dbb27fad6f3e407f2f1ec4cbbdf36f50f4b8e32/src/v8.js#L73

**Comment by romgrk** [comment]
Sorry I don't understand the issue here, did you forgot to add more details? :)

**Comment by lordnox** [comment]
I don’t know why, github changed the line number...

You forgot to export the label endpoint.

I am currently going through and rewriting some of your code in typescript, I need the typesafety. Not sure if you would like a rewrite PR, if not I‘d publish a secondary npm package.

**Comment by romgrk** [comment]
Right, I've exported it in 38aa73d.

About the typescript: I'd take it if it doesn't hurt readability too much, and the build setup is simple. But if you plan to maintain and publish a different package, I would consider that in favour of merging your typescript work. This package owns the `todoist` name so I'd rather have it be the best implementation rather than some half-baked implementation.

Also note that the package is currently in beta state, some calls are untested and some of them I know will fail (eg liveNotifications).
